// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Torna opcional durante o build - Prisma Client não precisa da URL para gerar tipos
    url: env("POSTGRES_PRISMA_URL", { optional: true }),
  },
});
